mob-spawning:
  passive:
    ALLAY: true
    ARMADILLO: true
    AXOLOTL: true
    BAT: true
    CAMEL: true
    CAT: true
    CHICKEN: true
    COD: true
    COW: true
    DONKEY: true
    FROG: true
    GLOW_SQUID: true
    HORSE: true
    MOOSHROOM: true
    MULE: true
    OCELOT: true
    PARROT: true
    PIG: true
    PUFFERFISH: true
    RABBIT: true
    SALMON: true
    SHEEP: true
    SKELETON_HORSE: true
    SNIFFER: true
    SNOW_GOLEM: true
    SQUID: true
    STRIDER: true
    TADPOLE: true
    TROPICAL_FISH: true
    TURTLE: true
    VILLAGER: true
    WANDERING_TRADER: true
  neutral:
    BEE: true
    CAVE_SPIDER: true
    DOLPHIN: true
    DROWNED: true
    ENDERMAN: true
    FOX: true
    GOAT: true
    IRON_GOLEM: true
    LLAMA: true
    PANDA: true
    PIGLIN: true
    POLAR_BEAR: true
    SPIDER: true
    TRADER_LLAMA: true
    WOLF: true
    ZOMBIFIED_PIGLIN: true
  hostile:
    BLAZE: true
    CREEPER: true
    ENDERMITE: true
    EVOKER: true
    GHAST: true
    GUARDIAN: true
    HOGLIN: true
    HUSK: true
    MAGMA_CUBE: true
    PHANTOM: true
    PIGLIN_BRUTE: true
    PILLAGER: true
    RAVAGER: true
    SHULKER: true
    SILVERFISH: true
    SKELETON: true
    SLIME: true
    STRAY: true
    VEX: true
    VINDICATOR: true
    WARDEN: true
    WITCH: true
    WITHER_SKELETON: true
    ZOGLIN: true
    ZOMBIE: true
    ZOMBIE_VILLAGER: true
  bosses:
    ELDER_GUARDIAN: true
    ENDER_DRAGON: true
    WITHER: true